import { ElButton } from "element-plus/es/components/button/index";
import { ElDrawer } from "element-plus/es/components/drawer/index";
import { ElDropdown, ElDropdownItem, ElDropdownMenu } from "element-plus/es/components/dropdown/index";
import { ElForm, ElFormItem } from "element-plus/es/components/form/index";
import { ElInput } from "element-plus/es/components/input/index";
import { ElOption, ElSelect } from "element-plus/es/components/select/index";
import { ElPagination } from "element-plus/es/components/pagination/index";
import { ElRadioButton, ElRadioGroup } from "element-plus/es/components/radio/index";
import { ElSkeleton } from "element-plus/es/components/skeleton/index";
import { ElTable, ElTableColumn } from "element-plus/es/components/table/index";
import { ElTag } from "element-plus/es/components/tag/index";
import "element-plus/dist/index.css";
import "highlight.js/styles/github.css";
import { createPinia } from "pinia";
import { createApp } from "vue";
import App from "./App.vue";
import { i18n } from "./i18n";
import { router } from "./router";
import "./styles/variables.css";
import "./styles/element-plus.css";
import "./styles/base.css";

const app = createApp(App);

app.use(createPinia());
app.use(router);
app.use(i18n);
app.use(ElButton);
app.use(ElDrawer);
app.use(ElDropdown);
app.use(ElDropdownItem);
app.use(ElDropdownMenu);
app.use(ElForm);
app.use(ElFormItem);
app.use(ElInput);
app.use(ElOption);
app.use(ElPagination);
app.use(ElRadioButton);
app.use(ElRadioGroup);
app.use(ElSelect);
app.use(ElSkeleton);
app.use(ElTable);
app.use(ElTableColumn);
app.use(ElTag);

app.mount("#app");
